
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTO = 3;
  public static final int EXTRA = 15;
  public static final int TIPO = 13;
  public static final int CORCHETESCERRADO = 24;
  public static final int LLAVESABIERTO = 21;
  public static final int RESTA = 28;
  public static final int UNIR = 12;
  public static final int PIE = 6;
  public static final int COMENTARIOS = 18;
  public static final int PORCENTAJE = 35;
  public static final int ETIQUETAS = 10;
  public static final int PUNTOCOMA = 4;
  public static final int DEFINICIONES = 2;
  public static final int EJEY = 9;
  public static final int CADENAS = 34;
  public static final int EJEX = 8;
  public static final int PARENTESISCERRADO = 20;
  public static final int TITULO = 7;
  public static final int SUMA = 27;
  public static final int EOF = 0;
  public static final int DECIMAL = 33;
  public static final int ESPACIOS = 17;
  public static final int VALORES = 11;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int CORCHETESABIERTO = 23;
  public static final int ENTEROS = 32;
  public static final int ERROR = 31;
  public static final int BARRA = 5;
  public static final int TOTAL = 14;
  public static final int PUNTO = 25;
  public static final int PARENTESISABIERTO = 19;
  public static final int LLAVESCERRADO = 22;
  public static final int CANTIDAD = 36;
  public static final int DIVISION = 30;
  public static final int EJECUTAR = 16;
  public static final int MULTIPLICACION = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINICIONES",
  "DOSPUNTO",
  "PUNTOCOMA",
  "BARRA",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "ESPACIOS",
  "COMENTARIOS",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "LLAVESABIERTO",
  "LLAVESCERRADO",
  "CORCHETESABIERTO",
  "CORCHETESCERRADO",
  "PUNTO",
  "COMA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ERROR",
  "ENTEROS",
  "DECIMAL",
  "CADENAS",
  "PORCENTAJE",
  "CANTIDAD"
  };
}

